package wf

type Queryuserdsbypid struct {
	DetailID           string  `xorm:"detailid" json:"detailid"`
	GridID             int     `xorm:"gridid" json:"gridid"`
	Pid                int     `xorm:"pid" json:"pid"`
	SqlCol             string  `xorm:"sqlcol" json:"sqlcol"`
	SelectStr          string  `xorm:"selectstr" json:"selectstr"`
	SelectShow         string  `xorm:"select_show" json:"select_show"`
	Name               string  `xorm:"name" json:"name"`
	SortID             float64 `xorm:"sortid" json:"sortid"`
	IsEnable           int     `xorm:"isenable" json:"isenable"`
	IsSave             int     `xorm:"issave" json:"issave"`
	IsHide             int     `xorm:"ishide" json:"ishide"`
	IsRequired         int     `xorm:"isrequired" json:"isrequired"`
	IsReadOnly         int     `xorm:"isreadonly" json:"isreadonly"`
	ControlType        string  `xorm:"controltype" json:"controltype"`
	DataSource         string  `xorm:"datasource" json:"datasource"`
	DataSourceWhere    string  `xorm:"datasourcewhere" json:"datasourcewhere"`
	SqlDataType        string  `xorm:"sqldatatype" json:"sqldatatype"`
	EventByAuto        string  `xorm:"eventbyauto" json:"eventbyauto"`
	MathStr            string  `xorm:"mathstr" json:"mathstr"`
	DefaultValue       string  `xorm:"defaultvalue" json:"defaultvalue"`
	TargetRefCol       string  `xorm:"targetrefcol" json:"targetrefcol"`
	RefCol             string  `xorm:"refcol" json:"refcol"`
	SortType           string  `xorm:"sorttype" json:"sorttype"`
	IsSum              int     `xorm:"issum" json:"issum"`
	Fnumber            int     `xorm:"fnumber" json:"fnumber"`
	IsQueryShow        int     `xorm:"isqueryshow" json:"isqueryshow"`
	IsOnlyLast         int     `xorm:"isonlylast" json:"isonlylast"`
	IsShortQuery       int     `xorm:"isshortquery" json:"isshortquery"`
	IsSingle           int     `xorm:"issingle" json:"issingle"`
	IsAutoEx           int     `xorm:"isautoex" json:"isautoex"`
	IsExcelImport      int     `xorm:"isexcelimport" json:"isexcelimport"`
	IsNeedConvert      int     `xorm:"isneedconvert" json:"isneedconvert"`
	IsConvertByCode    int     `xorm:"isconvertbycode" json:"isconvertbycode"`
	IsConvertByName    int     `xorm:"isconvertbyname" json:"isconvertbyname"`
	DataFormat         string  `xorm:"dataformat" json:"dataformat"`
	SpecialSet         string  `xorm:"specialset" json:"specialset"`
	IsFinance          int     `xorm:"isfinance" json:"isfinance"`
	ShowDiscard        int     `xorm:"showdiscard" json:"showdiscard"`
	IsCodeName         int     `xorm:"iscode_name" json:"iscode_name"`
	RegHtmlAttr        string  `xorm:"reghtmlattr" json:"reghtmlattr"`
	LabelAlign         string  `xorm:"labelalign" json:"labelalign"`
	TextAlign          string  `xorm:"textalign" json:"textalign"`
	ControlWidth       string  `xorm:"controlwidth" json:"controlwidth"`
	IsFullName         int     `xorm:"isfullname" json:"isfullname"`
	IsLoadByHtml       int     `xorm:"isloadbyhtml" json:"isloadbyhtml"`
	LoadByHtmlFormat   string  `xorm:"loadbyhtmlformat" json:"loadbyhtmlformat"`
	IsMobile           int     `xorm:"ismobile" json:"ismobile"`
	CreateDate         string  `xorm:"create_date" json:"create_date"`
	Memo               string  `xorm:"memo" json:"memo"`
	IsPrint            int     `xorm:"isprint" json:"isprint"`
	ValidStr           string  `xorm:"validstr" json:"validstr"`
	IsUIhide           int     `xorm:"isuihide" json:"isuihide"`
	Isunautoselectshow int     `xorm:"isunautoselectshow" json:"isunautoselectshow"`
	HideMath           string  `xorm:"hidemath" json:"hidemath"`
	RequireMath        string  `xorm:"requiremath" json:"requiremath"`
	ReadonlyMath       string  `xorm:"readonlymath" json:"readonlymath"`
	IsMobileSSP        int     `xorm:"ismobilessp" json:"ismobilessp"`
	IsmobileListshow   int     `xorm:"ismobile_listshow" json:"ismobile_listshow"`
	IsmobileMerge      int     `xorm:"ismobile_merge" json:"ismobile_merge"`
	IsmobileShowlab    int     `xorm:"ismobile_showlab" json:"ismobile_showlab"`
	IsmobileListtop    int     `xorm:"ismobile_listtop" json:"ismobile_listtop"`
	Opentype           string  `xorm:"opentype" json:"opentype"`
	MobileRangeID      string  `xorm:"mobilerangeid" json:"mobilerangeid"`
	IsMultiple         int     `xorm:"ismultiple" json:"ismultiple"`
	IsStanDs           int     `xorm:"isstands" json:"isstands"`
	DSGroupID          int     `xorm:"dsgroupid" json:"dsgroupid"`
	GridName           string  `xorm:"gridname" json:"gridname"`
	EntId              int     `xorm:"entid" json:"entid"`
}
