package logtype

//定义所有错误类型
const (
	Info                 = "普通信息"
	Config               = "配置被修改"
	ConfigWF             = "工作流被修改"
	ConfigForm           = "表单被修改"
	ConfigAccess         = "权限被修改"
	SaveErr              = "保存失败"
	SubmitErr            = "提交失败"
	DisCardErr           = "弃审失败"
	QueryErr             = "查询失败"
	DeleteErr            = "删除失败"
	CopyErr              = "拷贝失败"
	ParameterErr         = "参数值无效或不存在"
	QueryResultEmptyErr  = "未查询到数据"
	RedisCheckErr        = "Redis检查SQL失败"
	RedisLoadErr         = "Redis加载失败"
	RedisGetErr          = "Redis取值失败"
	RedisClearErr        = "Redis取值失败"
	BatchInsertErr       = "事务中执行Insert失败"
	BatchUpdateErr       = "事务中执行Update失败"
	ExecMoreSqlErr       = "批量执行SQL失败"
	ExecMoreSqlBrTranErr = "事务中批量执行SQL失败"
	ExecSqlErr           = "SQL执行失败"
	ExecSqlByTranErr     = "事务中SQL执行失败"
	ExecProcErr          = "存储过程执行失败"
	ExecProcByTranErr    = "存储过程执行失败"
	GetConnErr           = "获取数据库连接失败"
	GetIniErr            = "获取ini配置文件错误"
	CreateJsonErr        = "生成JSON字符串失败"
	CreateGsErr          = "生成公式失败"
	UnmarshalErr         = "解析JSON到对象"
	MarshalErr           = "序列化成JSON错误"
	NoDBErr              = "数据库未配置"
	CreateTableErr       = "创建SQL表错误"
	DataTypeErr          = "数据类型转换错误"
	FlowErr              = "流程配置错误"
	ExecEvent            = "用户事件被调用"
	EventErr             = "用户事件执行失败"
	RollbackErr          = "回滚失败"
	MenuVerErr           = "更新菜单版本失败"
	ApproveErr           = "审批错误"
	ReleaseErr           = "发布错误"
	SendCCMsgErr         = "发送抄送消息错误"
	SendWFMsgErr         = "发送审批消息错误"
	SendDDErr            = "发送钉钉错误"
	SendEmailErr         = "发送邮件错误"
	SendWeChatErr        = "发送微信错误"
	SendWeaverErr        = "发送泛微错误"
	SendWaitTaskErr      = "发送待办错误"
	SendResult           = "发送消息结果"
	ExLoginErr           = "AppId 登录失败"
	RequestEXWFErr       = "调用外部审批流失败"
)
